title: Lost in Space
hero_image: images/banner.png
subtitle: No subtitle needed
description: Learn how to program your own animation!
original_url: https://codeclubprojects.org/en-GB/scratch/rock-band
theme: cc-prototype
published: false
steps:
  - title: Introduction
    duration: 60
