title: Lost in Space
hero_image: images/banner.png
description: Learn how to program your own animation!
original_url:
theme: cc-prototype
duration: 2
published: false
listed: false
copyedit: false
interests:
technologies:
steps:
  - title: Introduction
  - title: What you'll need
  - title: "Animating a spaceship"
  - title: "Animating using loops"
  - title: "Floating monkey"
  - title: "Bouncing asteroids"
  - title: "Shining stars"
  - title: "Challenge: Make your own animation"
